### ISSUE TITLE
How to change num_segments?

### ISSUE THREAD

**Issue by shajie17** [zhang-can/ECO-pytorch#17]
hello,I want to set num_segments to 16,I have  tried to change 
args.num_segments=16,but it's wrong.Can you tell me what should I do?

and the base_model include one segments(input one  frame ) or four segment network?
thank you very much

**Comment by zhang-can** [comment]
Hi @shajie17 ,

Could you please show me the error log info?

**Comment by shajie17** [comment]
@zhang-can sorry,I havn't log info,but 
Traceback (most recent call last):
  File "/home/shajie/PycharmProjects/ECO-pytorch/main.py", line 339, in <module>
    main()
  File "/home/shajie/PycharmProjects/ECO-pytorch/main.py", line 139, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "/home/shajie/PycharmProjects/ECO-pytorch/main.py", line 185, in train
    output = model(input_var)
  File "/home/shajie/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shajie/.local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/shajie/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shajie/PycharmProjects/ECO-pytorch/models.py", line 324, in forward
    base_out = self.new_fc(base_out)
  File "/home/shajie/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shajie/.local/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/shajie/.local/lib/python2.7/site-packages/torch/nn/functional.py", line 992, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [1 x 2048], m2: [512 x 101] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:249



it's ok?

**Comment by zhang-can** [comment]
Hi @shajie17 ,

Please use our latest code, this can solve your problem:
https://github.com/mzolfaghari/ECO-pytorch

**Comment by jhlee301** [comment]
> Hi @shajie17 ,
> 
> Please use our latest code, this can solve your problem:
> https://github.com/mzolfaghari/ECO-pytorch

Hi @zhang-can 

I followed your link (forked version of your code), but I encountered same issue.
After I slightly modified the code, I am able to run the ECO model using 'num_segments=16'.
But, running with 'num_segments=3' is hard because the dimension issue.

Is there any solution for this problem?
