### ISSUE TITLE
分割ucf101的问题

### ISSUE THREAD

**Issue by superHcc** [zhang-can/ECO-pytorch#55]
Traceback (most recent call last):
  File "gen_dataset_lists.py", line 100, in <module>
    lists = build_split_list(split_tp, f_info, i, shuffle)
  File "/home/s18hc/ECO-pytorch-master/ECO-pytorch-master/pyActionRecog/benchmark_db.py", line 58, in build_split_list
    train_rgb_list, train_flow_list = build_set_list(split[0])
  File "/home/s18hc/ECO-pytorch-master/ECO-pytorch-master/pyActionRecog/benchmark_db.py", line 48, in build_set_list
    frame_dir = frame_info[0][item[0]]
KeyError: 'v_ApplyEyeMakeup_g08_c01

有没有人在分割ucf101数据集的时候出的问题    看了两天实在没找到

**Comment by zaf05** [comment]
我也有事这个问题

**Comment by zaf05** [comment]
我也是这个问题，请问你解决了吗

**Comment by superHcc** [comment]
> 我也是这个问题，请问你解决了吗

你要把每个视频分割成一个只放帧数的文件夹，然后再处理

**Comment by zaf05** [comment]
你好，请问是吧视频抽帧后，1.按照名字放在对应文件夹下面，就可以了吗？；2.还需要提取光流吗，第一次搞这个请多指教

**Comment by tejasvi** [comment]
@zaf05 No.

**Comment by bravewhh** [comment]
你好，请问你这个问题解决了吗？最后怎么解决的呢？怎样才能把每个视频分割成一个只放帧数的文件夹呢

**Comment by tejasvi** [comment]
@bravewu-sen There is a mismatch between the list and the folder names for certain categories. I would suggest trying with a small subset of data, say using only two categories to debug it further :)

**Comment by bravewhh** [comment]
> @bravewu-sen There is a mismatch between the list and the folder names for certain categories. I would suggest trying with a small subset of data, say using only two categories to debug it further :)

这个mismatch是不是他的testlist的问题呢？

**Comment by bravewhh** [comment]
我看trainlist跟testlist里面不对应啊

**Comment by tejasvi** [comment]
@bravewu-sen I don't precisely remember, the mismatch was due to wrong capitalization or extra spaces in the test list. I didn't experiment with the test list, which I sure expect to be different from the train list. You can experiment with a single category data (and construct the corresponding list) and see if it works. Then you can binary search for the problematic categories.

**Comment by Zhangxinnian** [comment]
@superHcc 您好，您的意思是要把每个类别下的视频文件抽帧，并存放在对应的文件夹下，我这样理解对吗

**Comment by JasonYangZi** [comment]
@Zhangxinnian 你的问题解决了吗？我遇到了同样的问题，可我已经把视频全部抽帧了，我的指令为 python gen_dataset_lists.py ucf101 /home/jiang/videos/ucf101/jpg/，其中jpg目录下有全部的帧数据如"jpg/ApplyEyeMakeup/v_ApplyLipstick_g08_c01/img_00010.jpg"

**Comment by Zhangxinnian** [comment]
> @Zhangxinnian你的问题解决了吗？我遇到了同样的问题，可我已经把视频全部抽帧了，我的指令为python gen_dataset_lists.py ucf101 / home / jiang / videos / ucf101 / jpg /，其中jpg目录下有全部的帧数据如“ jpg / ApplyEyeMakeup / v_ApplyLipstick_g08_c01 / img_00010.jpg”

您好，很抱歉具体的更改部分我忘记了，图片的格式和路径都是对的，可以关注一下gen_datasset_lists.py文件里面的lists = build_split_list(split_tp,f_info,i,shuffle)这块，调试一下，frame_dir=frame_info[0][iteam[0]]是否是你的/ home/jiang/videos/ ucf101/jpg/ApplyEyeMakeup/v_ApplyLipstick_g08_c01 这个路径对了，下边的rgb_cnt才会统计。

**Comment by dandingol03** [comment]
@superHcc 哥们你咋解决的，我也是一样问题。thanks in advance~

**Comment by dandingol03** [comment]
把输入路径改成【~/eng/dataset/UCF-101/*/】这种格式，因为生成list的时候是用glob.glob遍历的

**Comment by 1W2111** [comment]
新答案：把gen_label_ucf101.py文件中的.split('\\')改成.split('/')就能解决问题。大概有三处

**Comment by zhangtou** [comment]
> 新答案：把gen_label_ucf101.py文件中的.split（'\'）改成.split（'/'）就能解决问题。大概有三处

你好，感谢你的回答，想再请教您一个问题，希望有空的时候能帮忙看一下。在工程里ucf101_splits文件夹下有几个.txt文件，我没看懂testlist.txt 和trainlist.txt 有什么用，我发现两类txt里有的数据是重复的。我刚开始以为是testlist.txt 和trainlist.txt 存的就是划分好的训练集和验证集的视频名称，但是它里面有重复的我就蒙了
![image](https://github.com/zhang-can/ECO-pytorch/assets/50612347/22f4d419-5b00-4482-8ea6-b4329d017c10)

**Comment by 1W2111** [comment]
我目前的理解如下：（希望能帮到你）
trainlist01数据量+testlist01数据量=ucf101总数据量；
trainlist02数据量+testlist02数据量=ucf101总数据量；
03也是如此。


gen-label-ucf101.py文件也会依据这六个文件，生成三个标签文件，分别对应01的两个txt文件，02的两个txt文件以及03的两个txt文件。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月3日(周六) 晚上10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhang-can/ECO-pytorch] 分割ucf101的问题 (#55)




  
新答案：把gen_label_ucf101.py文件中的.split（''）改成.split（'/'）就能解决问题。大概有三处
  
你好，感谢你的回答，想再请教您一个问题，希望有空的时候能帮忙看一下。在工程里ucf101_splits文件夹下有几个.txt文件，我没看懂testlist.txt 和trainlist.txt 有什么用，我发现两类txt里有的数据是重复的。我刚开始以为是testlist.txt 和trainlist.txt 存的就是划分好的训练集和验证集的视频名称，但是它里面有重复的我就蒙了

**Comment by zhangtou** [comment]
> 我目前的理解如下：（希望能帮到你） trainlist01数据量+testlist01数据量=ucf101总数据量； trainlist02数据量+testlist02数据量=ucf101总数据量； 03也是如此。 gen-label-ucf101.py文件也会依据这六个文件，生成三个标签文件，分别对应01的两个txt文件，02的两个txt文件以及03的两个txt文件。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年6月3日(周六) 晚上10:11 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [zhang-can/ECO-pytorch] 分割ucf101的问题 (#55) 新答案：把gen_label_ucf101.py文件中的.split（''）改成.split（'/'）就能解决问题。大概有三处 你好，感谢你的回答，想再请教您一个问题，希望有空的时候能帮忙看一下。在工程里ucf101_splits文件夹下有几个.txt文件，我没看懂testlist.txt 和trainlist.txt 有什么用，我发现两类txt里有的数据是重复的。我刚开始以为是testlist.txt 和trainlist.txt 存的就是划分好的训练集和验证集的视频名称，但是它里面有重复的我就蒙了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

感谢你的回答，我明白了。数据集被随机划分为测试集和训练集，这里是随机划分了3次（就有点交叉验证那种感觉）。

还想请问一个问题，请问你们在哪找的预训练权重，我在工程里看到的要么无法下载，要么只有v1版本的
![image](https://github.com/zhang-can/ECO-pytorch/assets/50612347/d0d386b6-abe3-44cb-b77f-154cc303a925)

**Comment by 1W2111** [comment]
我是在README文件里找到的预训练模型，里面会有不同的预训练模型链接，直接下载就行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月10日(周六) 晚上7:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhang-can/ECO-pytorch] 分割ucf101的问题 (#55)




  
我目前的理解如下：（希望能帮到你） trainlist01数据量+testlist01数据量=ucf101总数据量； trainlist02数据量+testlist02数据量=ucf101总数据量； 03也是如此。 gen-label-ucf101.py文件也会依据这六个文件，生成三个标签文件，分别对应01的两个txt文件，02的两个txt文件以及03的两个txt文件。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年6月3日(周六) 晚上10:11 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [zhang-can/ECO-pytorch] 分割ucf101的问题 (#55) 新答案：把gen_label_ucf101.py文件中的.split（''）改成.split（'/'）就能解决问题。大概有三处 你好，感谢你的回答，想再请教您一个问题，希望有空的时候能帮忙看一下。在工程里ucf101_splits文件夹下有几个.txt文件，我没看懂testlist.txt 和trainlist.txt 有什么用，我发现两类txt里有的数据是重复的。我刚开始以为是testlist.txt 和trainlist.txt 存的就是划分好的训练集和验证集的视频名称，但是它里面有重复的我就蒙了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
感谢你的回答，我明白了。数据集被随机划分为测试集和训练集，这里是随机划分了3次（就有点交叉验证那种感觉）。
 
还想请问一个问题，请问你们在哪找的预训练权重，我在工程里看到的要么无法下载，要么只有v1版本的

**Comment by zhangtou** [comment]
> 我是在README文件里找到的预训练模型，里面会有不同的预训练模型链接，直接下载就行
> [...](#)
> ---原始邮件--- 发件人： ***@***.***> 发送时间: 2023年6月10日(周六) 晚上7:52 收件人： ***@***.***>; 抄送： ***@***.******@***.***>; 主题： Re： [zhang-can/ECO-pytorch] 分割ucf101的问题 （#55） 我目前的理解如下：（希望能帮到你） trainlist01数据量+testlist01数据量=ucf101总数据量; trainlist02数据量+testlist02数据量=ucf101总数据量; 03也是如此。gen-label-ucf101.py 文件也会依据这六个文件，生成三个标签文件，分别对应01的两个txt文件，02的两个txt文件以及03的两个txt文件。 ... ---原始邮件--- 发件人： @.>发送时间： 2023年6月3日（周六） 晚上10：11 收件人： @.>;抄送： @.@.>;主题： Re： [zhang-can/ECO-pytorch] 分割ucf101的问题 （#55） 新答案：把gen_label_ucf101.py文件中的.split（''）改成.split（'/'）就能解决问题。大概有三处 你好，感谢你的回答，想再请教您一个问题，希望有空的时候能帮忙看一下。在工程里ucf101_splits文件夹下有几个.txt文件，我没看懂testlist.txt 和trainlist.txt 有什么用，我发现两类txt里有的数据是重复的。我刚开始以为是testlist.txt 和trainlist.txt 存的就是划分好的训练集和验证集的视频名称，但是它里面有重复的我就蒙了 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。您收到此消息是因为您发表了评论。消息 ID： @.***> 感谢你的回答，我明白了。数据集被随机划分为测试集和训练集，这里是随机划分了3次（就有点交叉验证那种感觉）。 还想请问一个问题，请问你们在哪找的预训练权重，我在工程里看到的要么无法下载，要么只有v1版本的 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您发表了评论。消息 ID： ***@***.***>

你好，抱歉这么旧才回复，之前在readme里找到了权重，但是版本有点老，由于我操作问题导致效果不好，现在随便找了一个权重，做了训练后在ucf101上的效果还行。后边使用自己数据集发现，效果差了很多，连训练集的acc都只有50%左右，验证集只有个20%左右。。。不知道这个是否和加载的模型权重有关（因为我用自己的数据集在c3d网络上跑过，训练集的acc是可以到80%以上的）
![image](https://github.com/zhang-can/ECO-pytorch/assets/50612347/b7172b66-0474-4e27-8366-b28bc3853f55)
![image](https://github.com/zhang-can/ECO-pytorch/assets/50612347/e8c3ae04-291c-4cd0-b333-1e802971c2ee)
![image](https://github.com/zhang-can/ECO-pytorch/assets/50612347/50685d93-0fb1-42fc-b7a2-dcab272b262b)

![image](https://github.com/zhang-can/ECO-pytorch/assets/50612347/50685d93-0fb1-42fc-b7a2-dcab272b262b)
