### ISSUE TITLE
KeyError: 'v_ApplyEyeMakeup_g08_c01' 这个怎么解决

### ISSUE THREAD

**Issue by zhanghaobucunzai** [zhang-can/ECO-pytorch#66]
python3 gen_dataset_lists.py ucf101 /user/pytorch/ECO-pytorch/UCF-101

Processing dataset ucf101:

- Parse frames under folder /user/pytorch/ECO-pytorch/UCF-101

- 0/101 videos parsed

- Frame folder analysis done
- Writing list files for training/testing
Traceback (most recent call last):
  File "gen_dataset_lists.py", line 100, in <module>
    lists = build_split_list(split_tp, f_info, i, shuffle)
  File "/user/pytorch/ECO-pytorch/pyActionRecog/benchmark_db.py", line 58, in build_split_list
    train_rgb_list, train_flow_list = build_set_list(split[0])
  File "/user/pytorch/ECO-pytorch/pyActionRecog/benchmark_db.py", line 48, in build_set_list
    frame_dir = frame_info[0][item[0]]
KeyError: 'v_ApplyEyeMakeup_g08_c01'

**Comment by yeboqxc** [comment]
你好，请问你解决这个问题了吗？我已经将视频转换成帧，目录结构这样ucf101/ApplyEyeMakeup--最后一个/v_ApplyEyeMakeup_g01_c01--最后一个/00001.jpg...最后一个，请问该如何解决这个问题呢？还是我的运行命令有问题？可以给点建议吗？谢谢

**Comment by yeboqxc** [comment]
Hello, have you solved this problem? I have converted the video into frames, the directory structure is like this ucf101/ApplyEyeMakeup--the last one/v_ApplyEyeMakeup_g01_c01--the last one/00001.jpg...the last one, how can I solve this problem? Or is there something wrong with my run command? Can you give some suggestions? thanks

**Comment by HuZia777** [comment]
0 videos parsed
frame folder analysis done
Traceback (most recent call last):
  File "gen_label_ucf101.py", line 99, in <module>
    lists = build_split_list(spl,f_info,i)
  File "gen_label_ucf101.py", line 88, in build_split_list
    train_rgb_list, train_flow_list = build_set_list(split[0])
  File "gen_label_ucf101.py", line 77, in build_set_list
    frame_dir = frame_info[0][item[0]]
KeyError: 'v_Biking_g08_c01'
I also have this problem,have you solved it?

**Comment by HuZia777** [comment]
> python3 gen_dataset_lists.py ucf101 /user/pytorch/ECO-pytorch/UCF-101
> 
> Processing dataset ucf101:
> 
> * Parse frames under folder /user/pytorch/ECO-pytorch/UCF-101
> * 0/101 videos parsed
> * Frame folder analysis done
> * Writing list files for training/testing
>   Traceback (most recent call last):
>   File "gen_dataset_lists.py", line 100, in 
>   lists = build_split_list(split_tp, f_info, i, shuffle)
>   File "/user/pytorch/ECO-pytorch/pyActionRecog/benchmark_db.py", line 58, in build_split_list
>   train_rgb_list, train_flow_list = build_set_list(split[0])
>   File "/user/pytorch/ECO-pytorch/pyActionRecog/benchmark_db.py", line 48, in build_set_list
>   frame_dir = frame_info[0][item[0]]
>   KeyError: 'v_ApplyEyeMakeup_g08_c01'

hi,have you solved this problem?
